spring.application.name=microservicio-viajes

# ==== MONGO DB ====
spring.data.mongodb.uri=mongodb://root:example@localhost:27018/viajesdb?authSource=admin

# Puerto del microservicio
server.port=8081
