# ---- VIAJES ----
spring.application.name=microservicio-viajes

# DB VIAJES (contenedor mysql_viajes publicado en 3308)
spring.datasource.url=jdbc:mysql://localhost:3308/db_viajes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=example
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto HTTP del microservicio (evitá chocar con otros)
server.port=8081

